version: '2'

services:
  db:
    build: dockerfiles/postgres/
  web:
    build: dockerfiles/django/
    ports:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "cp -r annotable/almond webclient/static/ && python3 manage.py runserver 0.0.0.0:8000 --settings=agdss.settings.common"


networks:  
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
