version: '2'

services:
  db:
    build: dockerfiles/postgres/
  web:
    build: dockerfiles/django/
    expose:
      - "8000"
    depends_on:
      - db
    volumes:
      - ./:/app
    #command: bash -c "sleep 3600"
    command: bash -c "cd /app/agdss && cp -r /app/annotable/small-tomatoes/ /app/webclient/static/ && sleep 3600"


networks:  
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
